site_name: Robótica Computacional - Insper
theme:
  name: active-handout-theme
  language: pt

extra:
  custom_variables:
    data_infra_linux: "TBA"
    data_infra_simulador: "TBA"
    data_infra_turtlebot3: "TBA"

markdown_extensions:
  - toc:
      toc_depth: 0
  - markdown.extensions.admonition
  - meta
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.details
  - pymdownx.tabbed
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.snippets:
      base_path: "content/"
  - pymdownx.superfences
  - pymdownx.magiclink
  - pymdownx.critic:
      mode: view
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.smartsymbols
  - attr_list
  - pymdownx.arithmatex:
      generic: true

plugins:
    - active-handout


nav:
    - index.md
    - Infra:
      - guias-infra/index.md
      - Linux:
        - guias-infra/ssd-linux/index.md
        - guias-infra/ssd-linux/recebi-meu-ssd.md
        - guias-infra/ssd-linux/primeiros-passos/index.md
        - guias-infra/ssd-linux/terminal-basico.md
        - guias-infra/ssd-linux/git-e-github/index.md
      - Robô Simulado:
        - guias-infra/simulador/index.md
      - Robô TurtleBot3:
        - guias-infra/turtlebot3/index.md
    - Módulos:
      - "00 - Introdução":
        - "Sobre o curso": modulos/00-intro/index.md
        - modulos/00-intro/atividade-dia1.md
        - "Para saber mais": modulos/00-intro/recursos-legais.md
      - modulos/01-imagens-e-matrizes/index.md
      - modulos/02-videos/index.md
      - modulos/03-visao/index.md
      - modulos/04-ROS-basico/index.md
    - Projetos:
      - projeto/index.md
