site_name: Robótica Computacional - Insper
theme:
  name: active-handout-theme
  locale: pt_BR

extra_css:
    - equipe.css

extra:
  custom_variables:
    data_infra_linux: "17/03"
    data_infra_simulador: "17/03"
    data_infra_turtlebot3: "17/03"
    repo_aps: https://github.com/Insper/robotica-computacional-aps
    repo_aps_git: https://github.com/Insper/robotica-computacional-aps.git
    data_final_APS: 07/04
    data_APS1: 24/02
    data_PF: 07/06


markdown_extensions:
  - toc:
      toc_depth: 0
  - markdown.extensions.admonition
  - meta
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.details
  - pymdownx.tabbed
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.snippets:
      base_path: "content/"
  - pymdownx.superfences
  - pymdownx.magiclink
  - pymdownx.critic:
      mode: view
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.smartsymbols
  - attr_list
  - pymdownx.arithmatex:
      generic: true

plugins:
    - active-handout
    - mknotebooks


nav:
    - index.md
    - Infra:
      - guias-infra/index.md
      - Linux:
        - guias-infra/ssd-linux/index.md
        - "Primeiro boot com SSD":
            - guias-infra/ssd-linux/recebi-meu-ssd/index.md
            - guias-infra/ssd-linux/recebi-meu-ssd/windows.md
            - guias-infra/ssd-linux/recebi-meu-ssd/mac-os.md
        - guias-infra/ssd-linux/primeiros-passos/index.md
        - guias-infra/ssd-linux/guia-linux/index.md
        - guias-infra/ssd-linux/git-e-github/index.md
      - Robô Simulado:
        - guias-infra/robo-simulado/index.md
      - Robô TurtleBot3:
        - guias-infra/turtlebot3/index.md
      - guias-infra/aps.md
    - Módulos:
      - modulos/index.md
      - "00 - Introdução":
        - "Sobre o curso": modulos/00-intro/index.md
        - modulos/00-intro/atividade-dia1.md
        - "Para saber mais": modulos/00-intro/recursos-legais.md
      - "01 - Imagens e Matrizes":
        - modulos/01-imagens-e-matrizes/index.md
        - "Atividades":
          - "Leitura de imagens": modulos/01-imagens-e-matrizes/atividade1.ipynb
          - "Percorrendo a imagem": modulos/01-imagens-e-matrizes/atividade2.ipynb
          - "Cookbook de Numpy": modulos/01-imagens-e-matrizes/atividade3.ipynb
          - "Segmentação de imagens por cor": modulos/01-imagens-e-matrizes/atividade4.ipynb
      - modulos/02-videos/index.md
      - modulos/03-visao/index.md
      - modulos/04-ROS-basico/index.md
    - Projetos:
      - projeto/index.md
