site_name: Robótica Computacional - Insper
site_url: https://insper.github.io/robotica-computacional/
theme:
  name: active-handout-theme
  locale: pt_BR

extra_css:
    - equipe.css

extra:
  custom_variables:
    data_infra_linux: "25/08"
    data_infra_simulador: "01/09"
    data_infra_turtlebot3: "01/09"
    repo_aps: https://github.com/Insper/robotica-computacional-aps
    repo_aps_git: https://github.com/Insper/robotica-computacional-aps.git
    data_final_APS: 28/03
    data_APS1: 25/08
    data_APS2: 14/09
    data_APS3: 25/09
    data_APS4: 13/11
    data_PF: 05/12
    data_AI: 02/10

markdown_extensions:
  - toc:
      toc_depth: 0
  - markdown.extensions.admonition
  - meta
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.details
  - pymdownx.tabbed
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.snippets:
      base_path: "content/"
  - pymdownx.superfences
  - pymdownx.magiclink
  - pymdownx.critic:
      mode: view
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.smartsymbols
  - attr_list
  - pymdownx.arithmatex:
      generic: true

plugins:
    - active-handout
    - mknotebooks

nav:
    - index.md
    - "Critérios de Aprovação": criterios.md
    - "Sobre as APS": aps.md


    - Unidade 1:
      - Módulo 1 - Introdução ao Curso: 
        - modulos/01-intro/index.md
        - "Atividade Dia 1": modulos/01-intro/atividade-dia1.md
        - "Para Saber Mais": modulos/01-intro/recursos-legais.md
        - Atividades:
          - 1 - Infra:
            - "Começe Aqui!": modulos/01-intro/atividades/guias-infra/index.md
            - 1.1 - Linux:
              - "Início": modulos/01-intro/atividades/guias-infra/ssd-linux/index.md
              - "Primeiro boot com SSD":
                  - "Primeiro Boot": modulos/01-intro/atividades/guias-infra/ssd-linux/recebi-meu-ssd/index.md
                  - "Primeiro Boot - Windows": modulos/01-intro/atividades/guias-infra/ssd-linux/recebi-meu-ssd/windows.md
                  - "Primeiro Boot - MAC": modulos/01-intro/atividades/guias-infra/ssd-linux/recebi-meu-ssd/mac-os.md
              - "Meu SSD subiu, e agora?": modulos/01-intro/atividades/guias-infra/ssd-linux/primeiros-passos/index.md
              - "Guia básico de Linux": modulos/01-intro/atividades/guias-infra/ssd-linux/guia-linux/index.md
              - "Configure o seu Git": modulos/01-intro/atividades/guias-infra/ssd-linux/git-e-github/index.md
              # - "Pull Template": modulos/01-intro/atividades/guias-infra/ssd-linux/git-e-github/pull_template.md
            - 1.2 - Robô Simulado: modulos/01-intro/atividades/guias-infra/robo-simulado/index.md
            - 1.3 - Robô TurtleBot3: modulos/01-intro/atividades/guias-infra/turtlebot3/index.md
          - 2 - Revisão Python: 
            - "2.1 - Introdução à Classes no Python": modulos/01-intro/atividades/21-classes.ipynb
            - "2.2 - Dicionario e Funções": modulos/01-intro/atividades/22-funcoes.ipynb
        - APS 1:
          - "Enunciado": modulos/01-intro/aps/enunciado.md
          - "Checagem da Infra": modulos/01-intro/atividades/guias-infra/checagem.md

      - Módulo 2 - Introdução à ROS 2:
        - modulos/02-intro-ros/index.md
        - Atividades:
          - "1 - Pacotes e Comandos": modulos/02-intro-ros/atividades/1-package.md
          - "2 - Topicos na ROS": modulos/02-intro-ros/atividades/2-topicos.md
          - "3 - Criando um Pacote": modulos/02-intro-ros/atividades/3-creating-package.md
          - "4 - Pubshisher e Subscriber na ROS": modulos/02-intro-ros/atividades/4-pub-sub.md
        - APS 2:
          - "Enunciado": modulos/02-intro-ros/aps/enunciado.md

      - Módulo 3 - Controlando o Robô:
        - modulos/03-laser-e-robo/index.md
        - Atividades:
          - "Máquina de Estados": modulos/03-laser-e-robo/atividades/0-maquina-de-estados.md
          - "Estrutura Básica de um Nó":
            - "Estrutura Básica de um Nó": modulos/03-laser-e-robo/atividades/1-estrutura-basica.md
            - "Download > Nó Básico": modulos/03-laser-e-robo/util/base.py
            - "Download > Nó de Controle do Robô": modulos/03-laser-e-robo/util/base_control.py
          - "Entendendo a Odometria": modulos/03-laser-e-robo/atividades/2-odometria.md
          - "Visualização na ROS": modulos/03-laser-e-robo/atividades/3-visualizacao.md
          - "Entendendo o Laser": modulos/03-laser-e-robo/atividades/4-laser.md
          - "Salvando Eventos na ROS": modulos/03-laser-e-robo/atividades/5-rosbag.md
        - APS 3:
          - "Enunciado": modulos/03-laser-e-robo/aps/enunciado.md


    - Unidade 2:
      - Módulo 4 - Imagens e Matrizes:
        - modulos/04-visao-p1/index.md
        - Atividades:
          - "1.1 - Leitura de Imagem e Webcam": modulos/04-visao-p1/atividades/1-leitura_e_webcam.ipynb
          - "1.2 - Corte e Criação de Imagens": modulos/04-visao-p1/atividades/2-corte_e_criacao.ipynb
          - "1.3 - ROI e NumPy": modulos/04-visao-p1/atividades/3-roi_e_numpy.ipynb
          - "1.4 - Segmentação de Imagens p1": modulos/04-visao-p1/atividades/4-segmentacao_1.ipynb
          - "1.5 - Segmentação de Imagens p2": modulos/04-visao-p1/atividades/5-segmentacao_2.ipynb
        - APS 4:
          - "Enunciado": modulos/04-visao-p1/aps/enunciado.md

      - Módulo 5 - Visão Robótica:
        - modulos/05-visao-p2/index.md
        - Atividades:
          - "1.1 - Refinamento de Máscaras de Segmentação": modulos/05-visao-p2/atividades/1-morfologa.ipynb
          - "1.2 - Identificação de Objetos": modulos/05-visao-p2/atividades/2-identificacao.ipynb
          - "1.3 - Exemplo de Resolução de Exercício": modulos/05-visao-p2/atividades/3-exemplos.ipynb
          - "1.4 - Visão na ROS 2": modulos/05-visao-p2/atividades/4-imagesub.ipynb
        - APS 5:
          - "Enunciado": modulos/05-visao-p2/aps/enunciado.md